---
title: "Code 1: prepare data"
subtitle: 'sexism on aut'
author: "natalia & dacarras"
date: '`r format(Sys.time(), "%a %b %d, %Y")`'
output:
  html_document:
    theme: paper
    highlight: kate
    toc: true
    toc_float:
      collapsed: false
      smooth_scroll: false
    fig_width: 10 
    fig_height: 8 
---

<style>
  .main-container {
    max-width: 1600px !important;
  }
  .list-group-item.active, 
  .list-group-item.active:focus, 
  .list-group-item.active:hover {
    background-color: #373334;
  }
</style>


```{r , echo=TRUE, include = FALSE}
# -----------------------------------------------
# general setup
# -----------------------------------------------

knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(dev = 'png')
options(knitr.kable.NA = '')
options(scipen = 9999)

rm(list = ls()) # remove all previous objects

# fonts
Sys.setenv(LANG="en_US.UTF-8")

# -----------------------------------------------
# get times
# -----------------------------------------------

start_time <- Sys.time()

# -----------------------------------------------
# local path
# -----------------------------------------------

# get local path from relative path
local_path <- function(x){
paste0(tools::file_path_as_absolute(x),'/')  
}



```

# Folder locations

```{r, echo=TRUE}

# -------------------------------------------------------------------
# folder locations
# -------------------------------------------------------------------

# -----------------------------------------------
# get local path from relative path
# -----------------------------------------------

local_path <- function(x){
paste0(tools::file_path_as_absolute(x),'/')  
}

# -----------------------------------------------
# dacarras folders
# -----------------------------------------------

data_folder   <- local_path(getwd())
output_folder <- local_path(getwd())

# -----------------------------------------------
# check folders
# -----------------------------------------------

list.files(data_folder)
list.files(output_folder)

# -----------------------------------------------
# load main library
# -----------------------------------------------

library(dplyr)

```

# Read files

```{r, echo=TRUE}

# -------------------------------------------------------------------
# open file
# -------------------------------------------------------------------

data_09 <- readRDS(paste0(data_folder, 'iccs_2009_stu_lat.rds'))
data_16 <- readRDS(paste0(data_folder, 'iccs_2016_stu_lat.rds'))

# -----------------------------------------------
# check data structure
# -----------------------------------------------

dplyr::glimpse(data_09)
dplyr::glimpse(data_16)

```


# Merge

## Variable selections and computes


```{r, echo=TRUE, warning=FALSE}

#------------------------------------------------------------------------------
# comparable variables
#------------------------------------------------------------------------------

# Note: table with variables goes here 
#       column 1 with variables from 2009
#       column 2 with variables from 2016
#       column 3 with comparable names

variable_table <- read.table(
text="
var_2009  var_2016  var_recode
COUNTRY   COUNTRY   cty
IDCNTRY   IDCNTRY   cod
IS2P24A   IS3G24A   ge1
IS2P24B   IS3G24B   ge2
IS2P24E   IS3G24E   ge3
IS2P24C   IS3G24C   ge4 
IS2P24D   IS3G24D   ge5 
IS2P24F   IS3G24F   ge6
LS2P02A   LS3G01A   au1
LS2P02B   LS3G01B   au2
LS2P02C   LS3G01C   au3
LS2P02D   LS3G01D   au4
LS2P02E   LS3G01E   au5
LS2P02F   LS3G01F   au6
LS2P03A   LS3G02A   au7
LS2P03B   LS3G02B   au8
LS2P03C   LS3G02C   au9
IS2G16A   NA_TEXT   op1
IS2G16B   IS3G17A   op2
IS2G16C   IS3G17B   op3
IS2G16D   IS3G17C   op4
IS2G16E   IS3G17D   op5
IS2G16F   IS3G17E   op6
IS2G16G   IS3G17F   op7
NA_TEXT   IS3G18A   cl1
NA_TEXT   IS3G18B   cl2
NA_TEXT   IS3G18C   cl3
NA_TEXT   IS3G18D   cl4
NA_TEXT   IS3G18E   cl5
NA_TEXT   IS3G18F   cl6
NA_TEXT   IS3G18G   cl7
IS2G07    IS3G07    edm
IS2G09    IS3G09    edp
HISCED    S_HISCED  edx   
HOMELIT   S_HOMLIT  bok
GENEQL    S_GENEQL  gen
AUTGOV    L_AUTGOV  aut
PV1CIV    PV1CIV    civ1
PV2CIV    PV2CIV    civ2
PV3CIV    PV3CIV    civ3
PV4CIV    PV4CIV    civ4
PV5CIV    PV5CIV    civ5
OPDISC    S_OPDISC  opd
NISB      S_NISB    ses
SAGE      S_AGE     age
SGENDER   S_GENDER  sex
id_k      id_k      id_k
id_s      id_s      id_s
id_j      id_j      id_j
id_i      id_i      id_i
wt        wt        wt
wi        wi        wi
wj        wj        wj
wh        wh        wh
wa1       wa1       wa1
wa2       wa2       wa2
wb1       wb1       wb1
wb2       wb2       wb2
ws        ws        ws
JKZONES   JKZONES   jkz
",header=TRUE)

# Note: not equivalent measures

# IS2G07    IS3G07    edm
# HOMELIT   S_HOMLIT  bok

#------------------------------------------------------------------------------
# display table
#------------------------------------------------------------------------------

knitr::kable(variable_table)

#------------------------------------------------------------------------------
# vectors of variable names
#------------------------------------------------------------------------------


names_09  <- as.character(variable_table[[1]])
names_16  <- as.character(variable_table[[2]])
names_var <- as.character(variable_table[[3]])

#------------------------------------------------------------------------------
# variable selection, for 2009
#------------------------------------------------------------------------------


sel_09 <- data_09 %>%
          dplyr::select(one_of(names_09)) %>%
          rename_at(colnames(.), ~names_var) %>%
          haven::zap_label() %>%
          labelled::remove_labels() %>%
          mutate(year = 2009) %>%
          glimpse(.)

#------------------------------------------------------------------------------
# variable selection, for 2016
#------------------------------------------------------------------------------

# remove non existing variable
names_16  <- names_16[names_16 != 'NA_TEXT']
names_var <- names_var[names_var != 'op1']


sel_16 <- data_16 %>%
          dplyr::select(one_of(names_16)) %>%
          rename_at(colnames(.), ~names_var) %>%
          haven::zap_label() %>%
          labelled::remove_labels() %>%
          mutate(year = 2016) %>%
          glimpse(.)


# Note: variable IS2G16G do not exist in 2016 
#       so that variable was removed from the recoded names


#------------------------------------------------
# compare variables names
#------------------------------------------------

setdiff(names(sel_09),names(sel_16))
# op1 is the only difference. 


```

## Merge waves

```{r, echo=TRUE, warning=FALSE}

#------------------------------------------------------------------------------
# merge data
#------------------------------------------------------------------------------

data_gen <- dplyr::bind_rows(sel_09, sel_16) %>%
            dplyr::glimpse()



```

## Create group variables

```{r, echo=TRUE, warning=FALSE}

#------------------------------------------------------------------------------
# create group variables for generating syntax with init
#------------------------------------------------------------------------------

#------------------------------------------------
# ordered groups
#------------------------------------------------

dplyr::count(data_gen, cty, year) %>%
mutate(ord = c(1,2,3,4,5,6,9,7,8,11,10)) %>%
arrange(ord) %>%
knitr::kable()



```

## Check clustering variables

```{r, echo=TRUE, warning=FALSE}

#------------------------------------------------------------------------------
# verify clustering
#------------------------------------------------------------------------------

#------------------------------------------------
# cluster id_i
#------------------------------------------------

r4sda::check_cluster_id(data_gen, cluster_1 = 'id_i', cluster_2 = 'id_j')

# Note: id_i is not unique, a unique id should be created

#------------------------------------------------
# cluster id_j
#------------------------------------------------

r4sda::check_cluster_id(data_gen, cluster_1 = 'id_j', cluster_2 = 'id_k')

# Note: id_j is unique

data_gen %>%
dplyr::select(cty, id_j) %>%
unique() %>%
dplyr::count(., cty)

#------------------------------------------------
# cluster id_s
#------------------------------------------------

r4sda::check_cluster_id(data_gen, cluster_1 = 'id_s', cluster_2 = 'id_k')

# Note: id_s is unique

data_gen %>%
dplyr::select(cty, id_s) %>%
unique() %>%
dplyr::count(., cty)


#------------------------------------------------
# cluster id_k
#------------------------------------------------

dplyr::count(data_gen, cty, year, id_k)

```


## Recodes and computes

```{r, echo=TRUE, warning=FALSE}

#------------------------------------------------------------------------------
# recode and computes
#------------------------------------------------------------------------------

#------------------------------------------------
# non equivalent measures and centering
#------------------------------------------------

data_gen <- dplyr::bind_rows(sel_09, sel_16) %>%
# mother tertiary education
mutate(etm = case_when(
    year == 2009 & edm == 6 ~ 0, # not complete ISCED 1
    year == 2009 & edm == 5 ~ 0, # ISCED 1 primary
    year == 2009 & edm == 4 ~ 0, # ISCED 2 lower secondary
    year == 2009 & edm == 3 ~ 0, # ISCED 3 upper secondary
    year == 2009 & edm == 2 ~ 0, # ISCED 4 post secondary, non tertiary
    year == 2009 & edm == 1 ~ 1, # ISCED 5A or 6 Tertiary Education
    year == 2016 & edm == 5 ~ 0, # not complete ISCED 2
    year == 2016 & edm == 4 ~ 0, # ISCED 2 lower secondary
    year == 2016 & edm == 3 ~ 0, # ISCED 3 upper secondary
    year == 2016 & edm == 2 ~ 0, # ISCED 4 post secondary, non tertiary
    year == 2016 & edm == 1 ~ 0, # ISCED 6-8 Tertiary Education
    )) %>%
# books at home
mutate(bkc = case_when(
    year == 2009 & bok == 0 ~ 0, # None or very few (0-10 books)
    year == 2009 & bok == 1 ~ 1, # Enough to fill one shelf (11–25 books)
    year == 2009 & bok == 2 ~ 2, # Enough to fill one bookcase (26–100 books)
    year == 2009 & bok == 3 ~ 3, # Enough to fill two bookcases (101–200 books)
    year == 2009 & bok == 4 ~ 4, # Enough to fill three or more bookcases (more than 200 books)
    year == 2009 & bok == 5 ~ 4, # Enough to fill three or more bookcases (more than 200 books)
    year == 2016 & bok == 0 ~ 0, # None or very few (0-10 books)
    year == 2016 & bok == 1 ~ 1, # Enough to fill one shelf (11–25 books)
    year == 2016 & bok == 2 ~ 2, # Enough to fill one bookcase (26–100 books)
    year == 2016 & bok == 3 ~ 3, # Enough to fill two bookcases (101–200 books)
    year == 2016 & bok == 4 ~ 4, # Enough to fill three or more bookcases (more than 200 books)
    year == 2016 & bok == 5 ~ 4, # Enough to fill three or more bookcases (more than 200 books)
    )) %>%
# groups
mutate(grp = case_when(
    cty == 'CHL' & year == 2009 ~ 1,
    cty == 'CHL' & year == 2016 ~ 2,
    cty == 'COL' & year == 2009 ~ 3,
    cty == 'COL' & year == 2016 ~ 4,
    cty == 'DOM' & year == 2009 ~ 5,
    cty == 'DOM' & year == 2016 ~ 6,
    cty == 'MEX' & year == 2009 ~ 7,
    cty == 'MEX' & year == 2016 ~ 8,
    cty == 'GTM' & year == 2009 ~ 9,
    cty == 'PRY' & year == 2009 ~ 10,
    cty == 'PER' & year == 2016 ~ 11,
    )) %>%
# reverse egalitarism items
mutate(ge1 = r4sda::reverse(ge1)) %>%
mutate(ge2 = r4sda::reverse(ge2)) %>%
mutate(ge3 = r4sda::reverse(ge3)) %>%
# reverse sexism items
mutate(ge4 = r4sda::reverse(ge4)) %>%
mutate(ge5 = r4sda::reverse(ge5)) %>%
mutate(ge6 = r4sda::reverse(ge6)) %>%
# reverse authoritarianism items
mutate(au1 = r4sda::reverse(au1)) %>%
mutate(au2 = r4sda::reverse(au2)) %>%
mutate(au3 = r4sda::reverse(au3)) %>%
mutate(au4 = r4sda::reverse(au4)) %>%
mutate(au5 = r4sda::reverse(au5)) %>%
mutate(au6 = r4sda::reverse(au6)) %>%
mutate(au7 = r4sda::reverse(au7)) %>%
mutate(au8 = r4sda::reverse(au8)) %>%
mutate(au9 = r4sda::reverse(au9)) %>%
# unique id
mutate(id_i = seq(1:nrow(.))) %>%
# change centering to the grand mean
mutate(main = 1) %>%
group_by(grp) %>%
## socio economic status
mutate(ses = r4sda::z_score(ses))        %>%  # mean score
mutate(ses_c = r4sda::c_mean(ses, id_j)) %>%  # means by group
mutate(ses_g = r4sda::c_mean(ses, id_k)) %>%  # grand mean             
mutate(ses_w = ses - ses_c   )    %>%  # centering within cluster
mutate(ses_m = ses - ses_g   )    %>%  # centering to the grand mean
mutate(ses_b = ses_c - ses_g )    %>%  # centered cluster means
## students sex
mutate(sex = sex) %>%  # mean score
mutate(sex_c = r4sda::c_mean(sex, id_j)) %>%  # means by group
mutate(sex_g = r4sda::c_mean(sex, id_k)) %>%  # grand mean           
mutate(sex_w = sex - sex_c   )    %>%  # centering within cluster
mutate(sex_m = sex - sex_g   )    %>%  # centering to the grand mean
mutate(sex_b = sex_c - sex_g )    %>%  # centered cluster means
## mother tertiary education
mutate(edu = etm) %>%
mutate(edu_c = r4sda::c_mean(edu, id_j)) %>%  # means by group
mutate(edu_g = r4sda::c_mean(edu, id_k)) %>%  # grand mean             
mutate(edu_w = edu - edu_c   )    %>%  # centering within cluster
mutate(edu_m = edu - edu_g   )    %>%  # centering to the grand mean
mutate(edu_b = edu_c - edu_g )    %>%  # centered cluster means
## books
mutate(bkz = r4sda::z_score(bkc))        %>%  # mean score
mutate(bkz_c = r4sda::c_mean(bkz, id_j)) %>%  # means by group
mutate(bkz_g = r4sda::c_mean(bkz, id_k)) %>%  # grand mean             
mutate(bkz_w = bkz - bkz_c   )    %>%  # centering within cluster
mutate(bkz_m = bkz - bkz_g   )    %>%  # centering to the grand mean
mutate(bkz_b = bkz_c - bkz_g )    %>%  # centered cluster means
## classroom discussion
mutate(opd = r4sda::z_score(opd))        %>%  # mean score
mutate(opd_c = r4sda::c_mean(opd, id_j)) %>%  # means by group
mutate(opd_g = r4sda::c_mean(opd, id_k)) %>%  # grand mean
mutate(opd_w = opd - opd_c   )    %>%  # centering within cluster
mutate(opd_m = opd - opd_g   )    %>%  # centering to the grand mean
mutate(opd_b = opd_c - opd_g )    %>%  # centered cluster means
## civ
mutate(civ = (civ1-500)/100)             %>%  # mean score
mutate(civ_c = r4sda::c_mean(civ, id_j)) %>%  # means by group
mutate(civ_g = r4sda::c_mean(civ, id_k)) %>%  # grand mean                     
mutate(civ_w = civ - civ_c  )  %>%  # centering within cluster
mutate(civ_m = civ - civ_g  )  %>%  # centering to the grand mean
mutate(civ_b = civ_c - civ_g)  %>%  # centered cluster means
## civ
mutate(civ1 = (civ1-500)/100)              %>%  # mean score
mutate(civ1_c = r4sda::c_mean(civ1, id_j)) %>%  # means by group
mutate(civ1_g = r4sda::c_mean(civ1, id_k)) %>%  # grand mean                     
mutate(civ1_w = civ1 - civ1_c  )  %>%  # centering within cluster
mutate(civ1_m = civ1 - civ1_g  )  %>%  # centering to the grand mean
mutate(civ1_b = civ1_c - civ1_g)  %>%  # centered cluster means
## pv2
mutate(civ2 = (civ2-500)/100)              %>%  # mean score
mutate(civ2_c = r4sda::c_mean(civ2, id_j)) %>%  # means by group
mutate(civ2_g = r4sda::c_mean(civ2, id_k)) %>%  # grand mean             
mutate(civ2_w = civ2 - civ2_c  )  %>%  # centering within cluster
mutate(civ2_m = civ2 - civ2_g  )  %>%  # centering to the grand mean
mutate(civ2_b = civ2_c - civ2_g)  %>%  # centered cluster means
## pv3
mutate(civ3 = (civ3-500)/100)              %>%  # mean score
mutate(civ3_c = r4sda::c_mean(civ3, id_j)) %>%  # means by group
mutate(civ3_g = r4sda::c_mean(civ3, id_k)) %>%  # grand mean             
mutate(civ3_w = civ3 - civ3_c  )  %>%  # centering within cluster
mutate(civ3_m = civ3 - civ3_g  )  %>%  # centering to the grand mean
mutate(civ3_b = civ3_c - civ3_g)  %>%  # centered cluster means
## pv4
mutate(civ4 = (civ4-500)/100)              %>%  # mean score
mutate(civ4_c = r4sda::c_mean(civ4, id_j)) %>%  # means by group
mutate(civ4_g = r4sda::c_mean(civ4, id_k)) %>%  # grand mean             
mutate(civ4_w = civ4 - civ4_c  )  %>%  # centering within cluster
mutate(civ4_m = civ4 - civ4_g  )  %>%  # centering to the grand mean
mutate(civ4_b = civ4_c - civ4_g)  %>%  # centered cluster means             
## pv5
mutate(civ5 = (civ5-500)/100)              %>%  # mean score
mutate(civ5_c = r4sda::c_mean(civ5, id_j)) %>%  # means by group
mutate(civ5_g = r4sda::c_mean(civ5, id_k)) %>%  # grand mean             
mutate(civ5_w = civ5 - civ5_c  )  %>%  # centering within cluster
mutate(civ5_m = civ5 - civ5_g  )  %>%  # centering to the grand mean
mutate(civ5_b = civ5_c - civ5_g)  %>%  # centered cluster means
## authoritarianism
mutate(aut = r4sda::z_score(aut))        %>%  # mean score
mutate(aut_c = r4sda::c_mean(aut, id_j)) %>%  # means by group
mutate(aut_g = r4sda::c_mean(aut, id_k)) %>%  # grand mean           
mutate(aut_w = aut - aut_c   )    %>%  # centering within cluster
mutate(aut_m = aut - aut_g   )    %>%  # centering to the grand mean
mutate(aut_b = aut_c - aut_g )    %>%  # centered cluster means
## geneql
mutate(gen = r4sda::z_score(gen))        %>%  # mean score
mutate(gen_c = r4sda::c_mean(gen, id_j)) %>%  # means by group
mutate(gen_g = r4sda::c_mean(gen, id_k)) %>%  # grand mean           
mutate(gen_w = gen - gen_c   )    %>%  # centering within cluster
mutate(gen_m = gen - gen_g   )    %>%  # centering to the grand mean
mutate(gen_b = gen_c - gen_g )    %>%  # centered cluster means
# ungroup data frame
ungroup() %>%
dplyr::glimpse()


```


## Countries dummy codes

```{r , echo=TRUE}

#------------------------------------------------------------------------------
# country dummies
#------------------------------------------------------------------------------

data_model <- data_gen %>%
             mutate(k1  = if_else(grp == 1,1,0)) %>%
             mutate(k2  = if_else(grp == 2,1,0)) %>%
             mutate(k3  = if_else(grp == 3,1,0)) %>%
             mutate(k4  = if_else(grp == 4,1,0)) %>%
             mutate(k5  = if_else(grp == 5,1,0)) %>%
             mutate(k6  = if_else(grp == 6,1,0)) %>%
             mutate(k7  = if_else(grp == 7,1,0)) %>%
             mutate(k8  = if_else(grp == 8,1,0)) %>%
             mutate(k9  = if_else(grp == 9,1,0)) %>%
             mutate(k10 = if_else(grp == 10,1,0)) %>%
             mutate(k11 = if_else(grp == 11,1,0))

#------------------------------------------------
# check dummies
#------------------------------------------------

dplyr::count(data_model, cty, year, k1, k2, k3, k4, k5, k6, k7, k8, k9, k10, k11)

```


# Save data

```{r , echo=TRUE}

#------------------------------------------------------------------------------
# save data
#------------------------------------------------------------------------------

saveRDS(data_model, paste0(data_folder,'data_gen.rds'))

```

